apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-todo-app
  namespace: workshop
  annotations:
    alb.networking.azure.io/alb-id: $RESOURCE_ID # Resource ID of the Application Load Balancer
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
  addresses:
  - type: alb.networking.azure.io/alb-frontend
    value: $FRONTEND_NAME # Frontend name from Application Gateway for container