apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: todo-frontend-route
  namespace: workshop
spec:
  parentRefs:
  - name: gateway-todo-app
    namespace: workshop
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend
      port: 3000